@echo off
cd /d "%~dp0"
echo Limpando venv antigo...
if exist venv rmdir /s /q venv
echo Criando novo venv...
py -m venv venv
call venv\Scripts\activate.bat
echo Atualizando pip...
python -m pip install --upgrade pip
echo Instalando Flask...
python -m pip install flask flask-sqlalchemy werkzeug
echo Iniciando ToDo Pro Senior...
python app.py
pause
